### ISSUE TITLE
Bonus rspec

### ISSUE THREAD

**Issue by schuylermaclay** [learn-co-curriculum/building-nested-hashes#11]
Fun lab,

First time raising an issue so let me know if I'm doing it wrong... 

 The "Bonus Code Along Challenge" instructions say: 

"Also! to enable these tests make sure to remove the x in front of the it block near the bottom."

There was no x and the test was running throughout the lab, not sure if the instructions should be deleted or the the RSPEC test should be disabled.

Thanks,
Schuyler

**Comment by AnnJohn** [comment]
Thanks @SchuylerMaclay for raising this issue. 

@SophieDeBenedetto can you look into this?

**Comment by SophieDeBenedetto** [comment]
hi @SchuylerMaclay and @AnnJohn, there is in fact an `x` in front of the test in the `spec/bonus_spec.rb`. It looks like this:

```
describe "#bonus" do 
  # remove the 'x' from the 'xit' below to activate this test!
    xit "uses the []= method to change the hero and heroine's status from alive to dead" do 
    expect(bonus[:montague][:hero][:status]).to eq("dead")
    expect(bonus[:capulet][:heroine][:status]).to eq("dead")

  end
end
```

When you run the test suite you'll see the test output in the terminal end with `7 examples, 6 failures, 1 pending`. The `1 pending` refers to the test above. To activate it remove the `x` from in front of `xit`.
