### ISSUE TITLE
Completed Lab not showing as complete

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/building-nested-hashes#12]
This is now the second time this has happened to me.

The first was in the new Using Arrays lab that Learn.co sneakily added in on Tuesday (11/10,15)
I completed the lab and the green circle is not filled in.

Now the building nested hashes lab (this one) is shown on the left the exact same way, no green circle.

**Comment by AnnJohn** [comment]
Hi @m00se333 please file a bug report for this. Thanks.
