### ISSUE TITLE
"Juliet" & other thoughts

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/building-nested-hashes#2]
I had a lot of fun with this! Yay. It was nice to be walked through the steps of building a nested data structure.

I noticed a few things:
- "Juliet" is misspelled as "Juliette" throughout the lab, including the tests.
- Ages are stored as strings, not as integers. Was this intentional?
- The newer syntax `key: value` was not used in directions (`:key => value`), or in the lab, even though it does appear in the first example about instructors before the code along.

I totally want to copy this premise for a nested data lab in iOS.

@SophieDeBenedetto

**Comment by SophieDeBenedetto** [comment]
- yikes, spelling is hard. thanks mark! 
- You will see both `key: value` and `:key => value` used interchangeably but I will add a note to that effect. 
- ages are strings b/c we don't usually do math on them. I will add a note.

**Comment by markedwardmurray** [comment]
It's a natural mistake! I think "Juliette" is the French form, while "Juliet" is the Italian.
