### ISSUE TITLE
Building Nested Hashes Lab - Friends is transposed for Romeo and Juliet

### ISSUE THREAD

**Issue by sjwakeman** [learn-co-curriculum/building-nested-hashes#22]
The Diagram has 2 friends for Romeo and 2 friends for Juliet.
Romeo's = Benvolio and Steven
Juliet's = Mercutio and Nurse

In the CODE ALONG CHALLENGE IV: NESTING FRIENDS AND ATTRIBUTES section it looks like Steven and Mercutio were transposed. In this section the 2 friends change in the text:
Romeo's = Benvolio and Mercutio
Juliet's = Steven and Nurse

The attributes are correct for Steven and Mercutio

Thanks!
![image](https://cloud.githubusercontent.com/assets/17987990/19944460/43e33a08-a0f9-11e6-85c8-2ea899dbdbd8.png)

**Comment by mjhough** [comment]
This is still an issue.

Also, 
Lady Capulet's age attribute is incorrect in the tests. It should be 52 as per the diagram, but it is 51.

**Comment by aviflombaum** [comment]
Fixed by ebcf3b5
